Update installer

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,4 +1,7 @@
-#!/bin/bash
+#! /bin/bash
+
+declare -a filelist=('t_archive' 't_backup' 't_backupquick' 't_makelist' 't_restore' 't_unarchive')
+error=0
 
 clear
 echo
@@ -7,18 +10,25 @@ echo "Installing Terminal Backup And Restore..."
 echo ────────────────────────────────────────────────────────────────────────────────────────
 echo
 
-cp t_archive /usr/local/bin/t_archive
-chmod 755 /usr/local/bin/t_archive
-cp t_backup /usr/local/bin/t_backup
-chmod 755 /usr/local/bin/t_backup
-cp t_backup /usr/local/bin/t_backupquick
-chmod 755 /usr/local/bin/t_backupquick
-cp t_makelist /usr/local/bin/t_makelist
-chmod 755 /usr/local/bin/t_makelist
-cp t_restore /usr/local/bin/t_restore
-chmod 755 /usr/local/bin/t_restore
-cp t_unarchive /usr/local/bin/t_unarchive
-chmod 755 /usr/local/bin/t_unarchive
+for file in "${filelist[@]}"; do
+  cp $file /usr/local/bin/$file
+  if [ $? == 0 ]; then
+    echo "+ [$file] installed successfully!"
+    chmod 755 /usr/local/bin/t_archive
+    if [ $? != 0 ]; then
+      echo "--- [$file] permissions could not be changed! Run [chmod 755 /usr/local/bin/$file] again."
+      error=1
+    fi
+  else
+    echo "--- [$file] install failed!!!"
+    error=1
+  fi
+done 
 
-echo DONE!
+echo
+if [ $error == 0 ]; then
+  echo "Install successful!"
+else
+  echo "*** Install failed! See above output for possible reasons why it failed. ***"
+fi
 echo
