Update to use /usr/local/bin execs and created installer

diff --git a/t_restore b/t_restore
--- a/t_restore
+++ b/t_restore
@@ -1,32 +1,37 @@
 #!/bin/bash
 
+wd=`pwd`
 filelist=".files"
+
+cd $wd
 
 clear
 echo ────────────────────────────────────────────────────────────────────────────────────────
-echo "Creating [$filelist] backup file list..."
+echo "Restoring files listed in [$filelist]..."
 echo ────────────────────────────────────────────────────────────────────────────────────────
 echo
 
-if [ -f "$filelist" ]; then
-  read -p "File list [$filelist] already exists. Overwrite? " yn
+if [ ! -f "$filelist" ]; then
+  echo "No file list exists! Run [makelist file1 file2 ...] to create the [$filelist] file list!"
   echo
-  case $yn in
-    [Yy]* ) echo "Removing [$filelist]..."; rm $filelist; echo; echo OK; echo;;
-    [Nn]* ) echo Goodbye.; echo; exit;;
-    * ) echo "You must answer yes or no."; echo; exit;;
-  esac
-  echo
+  exit
 fi
 
-for filename in "$@"; do
+while read filename; do
   shortname=${filename##*/}
 
-  if [ -f "$filename" ]; then
-    echo $filename >> $filelist
-    echo "+ File [$shortname] added to file list."
+  if [ -f "$shortname" ]; then
+    cp "$shortname" "$filename"
+    if [ $? == 0 ]; then
+      echo "+ File [$shortname] restored successfully!"
+    else
+      echo "--- File [$shortname] restore failed! ---"
+    fi
   else
     echo "--- File [$shortname] could not be found! ---"
   fi
   echo
-done
+done < $filelist
+
+#fullpath=$(echo "$filename" | sed 's/ /\\ /g')
+#fullpath=$(echo "${fullpath//[$'\t\r\n']}") # removes trailing returns, etc
